### ISSUE TITLE
Can't reconnect to the server after disconnecting

### ISSUE THREAD

**Issue by Skyyofficial** [AbdElAziz333/Pluto#19] opened 2023-03-14 09:58 UTC
The new patch still doesn't fix the bug that you can't reconnect to the server after disconnecting.

pluto-mc1.18.2-0.0.5
forgeVersion=40.2.0
mcVersion=1.18.2 
mcpVersion=20220404.173914

Server latest.log
`[14Mar2023 10:47:34.490] [Server thread/INFO] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: com.mojang.authlib.GameProfile@44e8c18d[id=<null>,name=SussyBaka__UwU,properties={},legacy=false] (/x.x.x.x:62991) lost connection: Disconnected`

server debug.log just gets this message from ftbbackups mod everytime i try to recconect (probably unrelated but I'll still include it just in case)
`[14Mar2023 10:47:39.161] [ftbbackups2_QuartzSchedulerThread/DEBUG] [net.creeperhost.ftbbackups.org.quartz.core.QuartzSchedulerThread/]: batch acquisition of 0 triggers`

client latest.log
`[14Mar2023 10:47:04.945] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to x.x.x.x, 25570`

client debug.log
`[14Mar2023 10:47:04.945] [Render thread/INFO] [net.minecraft.client.gui.screens.ConnectScreen/]: Connecting to x.x.x.x, 25570`
`[14Mar2023 10:47:04.969] 
[Netty Client IO #7/DEBUG] [net.minecraftforge.network.HandshakeHandler/FMLHANDSHAKE]: Starting new vanilla impl connection.`

**Comment by AbdElAziz333** [comment] 2023-04-01 19:32
okay then the issue is fixed in the 1.19.x version, then could someone test this update?
[1.18.2](https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.18.2-0.0.6)

**Comment by AbdElAziz333** [comment] 2023-04-02 00:44
can you please use the new update?
[1.18.2](https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.18.2-0.0.6)

**Comment by AbdElAziz333** [comment] 2023-04-02 01:53
can you please try the updates versions?
[1.19.3](https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.19.3-0.0.9) - [1.19.2](https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.19.2-0.0.9) [1.18.2](https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.18.2-0.0.6)

**Comment by AbdElAziz333** [comment] 2023-04-02 21:20
This issue is fixed in the newer versions, so will get closed, Thanks for All!

**Closed by AbdElAziz333** 2023-04-02 21:20 UTC
Labels: bug, pending release, in processing

**Comment by Raft08** [comment] 2023-04-10 23:46
Hello, I know I'm playing on an already out-dated version of minecraft but could it maybe possible to backport the fix to 1.18? If it's not possible I will totaly understand why.
